### ISSUE TITLE
AssertionError: assert self._min and self._max  # undated blocks must be part of sorted

### ISSUE THREAD

**Issue by wrvsrx** [SEIAROTg/autobean-format#3]
# Reproduce

1. install `autobean-format` via `pip install git+https://github.com/SEIAROTg/autobean-format`
1.  create `main.bean`

 ```
2022-05-29 * "a" "a"
    Assets:A  -200.00 CNY
    Expenses:A

2022-05-29 * "a" "a"
    Assets:A    -8.90 CNY
    Expenses:A

2022-05-30 * "a" "a"
    Assets:A     4.71 CNY
    Income:A

2022-05-30 * "a" "a"
    Assets:A  -200.00 CNY
    Assets:A
2022-05-30 * "a" "a"
    Assets:A  -200.00 CNY
    Assets:A
2022-05-31 * "a" "a"
    Income:A   -20.00 CNY
    Assets:A

2022-05-31 * "a" "a"
    Assets:A   -23.80 CNY
    Expenses:A
    Expenses:A

2022-05-02 * "a" "a"
    Assets:A   -38.00 CNY
    Expenses:A

2022-05-02 * "a" "a"
    Assets:A   -22.17 CNY
    Expenses:A

2022-05-03 * "a" "a"
    Assets:A   -13.00 CNY
    Expenses:A

2022-05-04 * "a" "a"
    Assets:A   -16.00 CNY
    Expenses:A

2022-05-05 * "a" "a"
    Assets:A   -55.00 CNY
    Expenses:A

2022-05-05 * "a" "a"
    Assets:A    -6.00 CNY
    Expenses:A

2022-05-05 open Income:A

2022-05-05 * "a" "a"
    Assets:A   666.00 CNY
    Income:A

2022-05-06 * "a" "a"
    Assets:A  -138.00 CNY
    Expenses:A
 ```

1. `autobean-format --sort main.bean`
1. It will throw error

```
❯ autobean-format --sort main.bean
Traceback (most recent call last):
  File "/nix/store/3cys3xbpgh5wck0vmrdbdivbqpbdah9q-python3.11-autobean-format-b1222f3ca1bfc771baca276876c3c6df99911bc4/bin/.autobean-format-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/a5haanvdfg1lfw13bnyx77d1ij6af4aw-python3-3.11.2-env/lib/python3.11/site-packages/autobean_format/main.py", line 80, in main
    formatted = formatter.format_file(file)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/a5haanvdfg1lfw13bnyx77d1ij6af4aw-python3-3.11.2-env/lib/python3.11/site-packages/autobean_format/main.py", line 53, in format_file
    formatter.format(file.model, self._parser, self._options, stream)
  File "/nix/store/a5haanvdfg1lfw13bnyx77d1ij6af4aw-python3-3.11.2-env/lib/python3.11/site-packages/autobean_format/formatter.py", line 16, in format
    for token in formatters.format(model, context):
  File "/nix/store/a5haanvdfg1lfw13bnyx77d1ij6af4aw-python3-3.11.2-env/lib/python3.11/site-packages/autobean_format/formatters/base.py", line 39, in format
    yield from formatter(model, context)
  File "/nix/store/a5haanvdfg1lfw13bnyx77d1ij6af4aw-python3-3.11.2-env/lib/python3.11/site-packages/autobean_format/formatters/file.py", line 75, in format_file
    blocks = sorting.sort_blocks(blocks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/a5haanvdfg1lfw13bnyx77d1ij6af4aw-python3-3.11.2-env/lib/python3.11/site-packages/autobean_format/internal/sorting.py", line 341, in sort_blocks
    results.extend(_sort_compartment(compartment))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/a5haanvdfg1lfw13bnyx77d1ij6af4aw-python3-3.11.2-env/lib/python3.11/site-packages/autobean_format/internal/sorting.py", line 319, in _sort_compartment
    blocks = _OrderedBlock.sort(blocks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/a5haanvdfg1lfw13bnyx77d1ij6af4aw-python3-3.11.2-env/lib/python3.11/site-packages/autobean_format/internal/sorting.py", line 110, in sort
    return list(cls.merge(sorted, unsorted))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/a5haanvdfg1lfw13bnyx77d1ij6af4aw-python3-3.11.2-env/lib/python3.11/site-packages/autobean_format/internal/sorting.py", line 292, in merge
    keyed_unsorted = [(block.simple_sort_key(), i, block) for i, block in enumerate(unsorted)]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/a5haanvdfg1lfw13bnyx77d1ij6af4aw-python3-3.11.2-env/lib/python3.11/site-packages/autobean_format/internal/sorting.py", line 292, in <listcomp>
    keyed_unsorted = [(block.simple_sort_key(), i, block) for i, block in enumerate(unsorted)]
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/a5haanvdfg1lfw13bnyx77d1ij6af4aw-python3-3.11.2-env/lib/python3.11/site-packages/autobean_format/internal/sorting.py", line 287, in simple_sort_key
    assert self._min and self._max  # undated blocks must be part of sorted
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by SEIAROTg** [comment]
Fixed in 448d82c.
